Repository maticnetwork/matic-docs, pull requests merged in 2022-07, with the labels that each got.

#957 chg: doc: Improved ``/docs/develop/getting-started.md``
  docs/develop/getting-started.md
Labels: enhancement, T1: Develop

#960 Generate Index Pages
  docs/develop/network-details/full-node-binaries.md
  docs/develop/network-details/full-node-deployment.md
  docs/develop/network-details/network.md
  docs/develop/network-details/snapshot-instructions-heimdall-bor.md
  docs/develop/network-details/technical-requirements.md
  sidebars.js
Labels: enhancement, T1: Develop, new page

#961 Update overview.md
  docs/nightfall/introduction/overview.md
Labels: bug

#956 Contributor Hub
  docs/contribute/bug-bounty-program.md
  docs/contribute/community-maintainers.md
  docs/contribute/contributor-guidelines.md
  docs/contribute/how-to-translate.md
  docs/contribute/non-native-speakers.md
  docs/contribute/orientation.md
  docs/contribute/tutorial-template.md
  docs/contribute/writing-style.md
  sidebars.js
Labels: enhancement, new page

#966 Adds text improvement
  docs/contribute/community-maintainers.md
  docs/contribute/contributor-guidelines.md
  docs/contribute/tutorial-template.md
  docs/contribute/writing-style.md
  sidebars.js
Labels: enhancement

#972 Generated index for Learning Section
  docs/home/architecture/matic-architecture.md
  docs/home/architecture/security-models.md
  docs/home/blockchain-basics/basics-accounts.md
  docs/home/blockchain-basics/basics-blockchain-types.md
  docs/home/blockchain-basics/basics-blockchain.md
  docs/home/blockchain-basics/basics-consensus-mechanism.md
  docs/home/blockchain-basics/basics-ethereum.md
  docs/home/blockchain-basics/basics-gas.md
  docs/home/blockchain-basics/basics-solidity.md
  docs/home/blockchain-basics/basics-transactions.md
  docs/home/blockchain-basics/import-account-to-metamask.md
  docs/home/blockchain-basics/matic.md
  docs/home/blockchain-basics/sidechain.md
  docs/home/polygon-basics/what-is-polygon.md
  docs/home/polygon-basics/what-is-proof-of-stake.md
  docs/maintain/polygon-basics/who-is-delegator.md
  docs/maintain/polygon-basics/who-is-validator.md
  sidebars.js
Labels: enhancement

#982 [Polygon Edge] Add DNS hostnames support info
  docs/edge/get-started/set-up-ibft-locally.md
  docs/edge/get-started/set-up-ibft-on-the-cloud.md
Labels: enhancement, T6: Edge

#983 [Polygon Edge] Add performance report from July
  docs/edge/performance-reports/test-history/test-2022-07-04.md
  sidebars.js
Labels: new page, T6: Edge

#985 Generated index for Validator section
  docs/avail/node/avail-node-management.md
  docs/maintain/glossary.md
  docs/maintain/polygon-basics/liquid-delegation.md
  docs/maintain/port_management.md
  docs/maintain/validate/change-signer-address.md
  docs/maintain/validate/faq/how-to.md
  docs/maintain/validate/faq/known-issues.md
  docs/maintain/validate/faq/validator-faq.md
  docs/maintain/validate/run-validator-ansible.md
  docs/maintain/validate/run-validator-binaries.md
  docs/maintain/validate/validator-commission-operations.md
  docs/maintain/validate/validator-node-system-requirements.md
  docs/maintain/validate/validator-staking-operations.md
  docs/maintain/validator/architecture.md
  docs/maintain/validator/core-components/bor-chain.md
  docs/maintain/validator/core-components/checkpoint-mechanism.md
  docs/maintain/validator/core-components/derivatives.md
  docs/maintain/validator/core-components/heimdall-chain.md
  docs/maintain/validator/core-components/key-management.md
  docs/maintain/validator/core-components/proposer-bonus.md
  docs/maintain/validator/core-components/proposer-producer-selection.md
  docs/maintain/validator/core-components/staking.md
  docs/maintain/validator/core-components/state-sync-mechanism.md
  docs/maintain/validator/core-components/transaction-fees.md
  docs/maintain/validator/responsibilities.md
Labels: enhancement

#984 [Polygon Edge] Migrate leftover opened PR-s
  docs/edge/additional-features/chainbridge/definitions.md
  docs/edge/additional-features/chainbridge/deploy-contracts.md
  docs/edge/additional-features/chainbridge/overview.md
  docs/edge/additional-features/chainbridge/requirements.md
  docs/edge/additional-features/chainbridge/roles-in-bridge.md
  docs/edge/additional-features/chainbridge/setup-erc20-transfer.md
  docs/edge/additional-features/chainbridge/setup-erc721-transfer.md
  docs/edge/additional-features/chainbridge/setup-relayer.md
  docs/edge/additional-features/chainbridge/setup.md
  docs/edge/additional-features/chainbridge/use-case-erc20-bridge.md
  docs/edge/additional-features/chainbridge/use-case-erc721-bridge.md
  docs/edge/consensus/pos-concepts.md
  docs/edge/get-started/json-rpc-commands.mdx
  sidebars.js
Labels: enhancement, new page, T6: Edge

#987 [Polygon Edge] Improves syncer module doc page
  docs/edge/architecture/modules/protocol.md
  docs/edge/architecture/modules/syncer.md
  sidebars.js
Labels: enhancement, T6: Edge

#989 Adds index to Integrator Section
  docs/integrate/install-gcp.md
  docs/integrate/network-detail.md
  docs/integrate/network.md
Labels: enhancement

#993 Adds Index to Edge doc
  sidebars.js
Labels: enhancement

#997 fixed typos
  docs/contribute/bug-bounty-program.md
Labels: enhancement

#998 Uploads updated Withdraw POS video
  docs/develop/wallets/polygon-web-wallet/web-wallet-v2-guide.md
  static/img/wallet/bridge.png
  static/img/wallet/challenge-completed.png
  static/img/wallet/checkpoint-arrived.png
  static/img/wallet/deposit-wallet.png
  static/img/wallet/pending-transaction.png
  static/img/wallet/plasma-progress.png
  static/img/wallet/transfer-completed.png
  static/img/wallet/waiting-checkpoint.png
  static/img/wallet/withdraw-POS-1.png
  static/img/wallet/withdraw-POS-2.png
  static/img/wallet/withdraw-POS.mp4
  static/img/wallet/withdraw-plasma-1.png
  static/img/wallet/withdraw-plasma-2.png
Labels: enhancement, PR: Please Review

#1003 Update network details | Add watchdata.io
  docs/develop/network-details/network.md
Labels: PR: Please Review, T1: Develop

#1004 Improved descriptions
  docs/nightfall/deployments/mainnet.md
  docs/nightfall/deployments/testnet.md
  docs/nightfall/protocol/actors.md
  docs/nightfall/protocol/challengers.md
  docs/nightfall/protocol/circuits.md
  docs/nightfall/protocol/commitments.md
  docs/nightfall/protocol/contracts.md
  docs/nightfall/protocol/proposers.md
  docs/nightfall/protocol/protocol.md
  docs/nightfall/protocol/secrets.md
  docs/nightfall/tools/nightfall-wallet.md
Labels: enhancement, T8: Nightfall

#991 Add metadata template
  docs/contribute/writing-style.md
  static/img/contribute/index-tile.png
Labels: enhancement, PR: Please Review

#1009 fixed some typos
  docs/integrate/ethereum-matic.md
Labels: enhancement

#1016 Includes instructions on how to run a node with Docker
  docs/develop/network-details/full-node-binaries.md
  docs/develop/network-details/full-node-deployment.md
  docs/develop/network-details/full-node-docker.md
  sidebars.js
  static/img/full-node-docker/heimdall-tree.png
  static/img/full-node-docker/heimdall-version.png
  static/img/full-node-docker/hello-world.png
  static/img/full-node-docker/space.png
  static/img/full-node-docker/term-access.png
Labels: PR: Please Review, T1: Develop, new page

#992 Added better descriptions to POS files
  docs/pos/bor/bor.md
  docs/pos/bor/consensus.md
  docs/pos/bor/core_concepts.md
  docs/pos/bor/overview.md
  docs/pos/contracts/delegation.md
  docs/pos/contracts/plasma_contracts/account_based_plasma.md
  docs/pos/contracts/plasma_contracts/important-contracts.md
  docs/pos/contracts/plasma_contracts/predicates.md
  docs/pos/contracts/stakingmanager.md
  docs/pos/heimdall/antehandler.md
  docs/pos/heimdall/checkpoint.md
  docs/pos/heimdall/encoder.md
  docs/pos/heimdall/modules/Auth.md
  docs/pos/heimdall/modules/Bank.md
  docs/pos/heimdall/modules/Bor.md
  docs/pos/heimdall/modules/Clerk.md
  docs/pos/heimdall/modules/Topup.md
  docs/pos/heimdall/modules/chainmanager.md
  docs/pos/heimdall/modules/checkpoint.md
  docs/pos/heimdall/modules/governance.md
  docs/pos/heimdall/modules/staking.md
  docs/pos/heimdall/overview.md
  docs/pos/heimdall/stdtx.md
  docs/pos/heimdall/transactions.md
  docs/pos/heimdall/types.md
  docs/pos/heimdall/validator-key-management.md
  docs/pos/heimdall/validators.md
  docs/pos/peppermint.md
  docs/pos/state-sync/how-does-state-sync-work.md
  docs/pos/state-sync/state-sync-mechamism.md
Labels: enhancement, PR: Please Review

#1012 [Polygon Edge] Update validator key info for Hashicorp Vault
  docs/edge/configuration/manage-private-keys.md
  docs/edge/configuration/secret-managers/set-up-hashicorp-vault.md
Labels: enhancement, PR: Please Review, T6: Edge

#1017 [Polygon Edge] Add FAQ
  docs/edge/faq/Contracts.md
  docs/edge/faq/Gas.md
  docs/edge/faq/Tokens.md
  docs/edge/faq/Validators.md
  docusaurus.config.js
  i18n/en/docusaurus-theme-classic/navbar.json
  sidebars.js
Labels: enhancement, T6: Edge
