Repository maticnetwork/matic-docs, pull requests merged in 2022-05, with the labels that each got.

#875 Update Bor Span Image
  docs/contribute/bor/bor.md
  static/img/Bor/bor-architecture.png
  static/img/Bor/bor-span.png
  static/img/Bor/matic_structure.png
Labels: PR: Changes Requested

#890 Update heimdall to 0.2.9
  docs/develop/network-details/full-node-deployment.md
  docs/integrate/full-node-binaries.md
  docs/integrate/full-node-deployment.md
  docs/integrate/install-gcp.md
  docs/maintain/validate/faq/validator-faq.md
  docs/maintain/validate/run-validator-ansible.md
  docs/maintain/validate/run-validator-binaries.md
  docs/maintain/validator/core-components/state-sync-mechanism.md
Labels: PR: Please Review

#902 Search engine live
  docusaurus.config.js
  package.json
  src/theme/SearchBar/algolia.css
  src/theme/SearchBar/index.js
  src/theme/SearchBar/styles.css
  yarn.lock
Labels: P0: Urgent

#900 Added Nightfall
  docs/nightfall/deployments/mainnet.md
  docs/nightfall/deployments/testnet.md
  docs/nightfall/faq/faq.md
  docs/nightfall/imgs/tools-wallet/cooling-off-vs-ready.png
  docs/nightfall/imgs/tools-wallet/deposit-click-transfer.png
  docs/nightfall/imgs/tools-wallet/deposit-tx-created-and-ready-to-be-sent.png
  docs/nightfall/imgs/tools-wallet/generate-mnemonic-create-wallet.png
  docs/nightfall/imgs/tools-wallet/nightfall-wallet-address.png
  docs/nightfall/imgs/tools-wallet/polygon-network-dropdown-nf.png
  docs/nightfall/imgs/tools-wallet/polygon-network.png
  docs/nightfall/imgs/tools-wallet/polygon-wallet-click-nf.png
  docs/nightfall/imgs/tools-wallet/send-nf.png
  docs/nightfall/imgs/tools-wallet/transactions.png
  docs/nightfall/imgs/tools-wallet/wallet-main-screen.png
  docs/nightfall/imgs/tools-wallet/wallet-state-synced.png
  docs/nightfall/imgs/tools-wallet/wallet-state-syncing.png
  docs/nightfall/introduction/introduction.md
  docs/nightfall/protocol/actors.md
  docs/nightfall/protocol/circuits.md
  docs/nightfall/protocol/commitments.md
  docs/nightfall/protocol/contracts.md
  docs/nightfall/protocol/proposers.md
  docs/nightfall/protocol/protocol.md
  docs/nightfall/protocol/secrets.md
  docs/nightfall/tools/nightfall-wallet.md
  sidebars.js
Labels: P1: Important

#908 testing different redirects
  docusaurus.config.js
Labels: enhancement

#909 Update RPC code block
  docs/develop/getting-started.md
Labels: T1: Develop

#913 Fix Glossary Link
  docs/maintain/delegate/delegate.md
Labels: bug

#914 Update getting-started.md
  docs/develop/wallets/getting-started.md
Labels: PR: Please Review
